services:

  postgres:
    image: postgres:15
    container_name: clickstream-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clickstream
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark-master:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/data
      - ./spark_jobs:/opt/spark_jobs

  spark-worker:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data:/data
      - ./spark_jobs:/opt/spark_jobs

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/clickstream
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
    ports:
      - "8088:8080"
    volumes:
      volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./generator:/opt/generator
      - /var/run/docker.sock:/var/run/docker.sock
    command: airflow standalone

volumes:
  postgres_data: